services:
  configserver:
    image: configserver:latest
    ports:
      - "8888:8888"
    networks:
      - my-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - my-network
  ms-product:
    image: ms-product:latest
    ports:
      - "9090:9090"
    environment:
      PORT: 9090
    networks:
      - my-network
  ms-identity-service:
    image: ms-identity-service:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    networks:
      - my-network
  ms-translate-service:
    image: ms-translate-service:latest
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
    networks:
      - my-network
  ms-payment-service:
    image: ms-payment-service:latest
    ports:
      - "8082:8082"
    environment:
      PORT: 8082
    networks:
      - my-network
  ms-user-service:
    image: ms-user-service:latest
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
    networks:
      - my-network
  ms-fraud-service:
    image: ms-fraud-service:latest
    ports:
      - "8084:8084"
    environment:
      PORT: 8084
    networks:
      - my-network
  apigateway:
    image: apigateway:latest
    ports:
      - "9191:9093"
    networks:
      - my-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_product
    ports:
      - "3306:3306"
    networks:
      - my-network
networks:
  my-network:
    driver: "bridge"
